default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  database: RoR
  username: joysi
  password: 1234
  host: 127.0.0.1
  port: 3306

test:
  <<: *default
  database: RoR_test
  username: joysi
  password: 1234
  host: 127.0.0.1
  port: 3306

production:
  <<: *default
  database: path/to/production/database
